name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    name: "tests & coverage"
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    env:
      COLUMNS: 120

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install hatch
      run: |
        python -m pip install hatch

    - name: Lint
      run: hatch run check

    - name: Coverage
      run: |
        export PYTHONPATH=.
        hatch run +py=${{ matrix.python-version }}  test:cov

    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml

